import Game.Support.Graph

namespace Game.Greedy

/-- An activity occupies the half-open interval from `start` to `finish`. -/
structure Activity where
  start : Nat
  finish : Nat

/-- `a` can be followed by `b` without overlap. -/
def Compatible (a b : Activity) : Prop :=
  a.finish ≤ b.start

/-- A candidate finishes no later than every activity in a collection. -/
def EarliestFinish (candidate : Activity) (activities : List Activity) : Prop :=
  ∀ activity ∈ activities, candidate.finish ≤ activity.finish

/-- A schedule is ordered and pairwise non-overlapping. -/
def IsSchedule (activities : List Activity) : Prop :=
  activities.Pairwise Compatible

/-- Binary codewords carried by the leaves of a Huffman tree. -/
inductive HuffmanTree where
  /-- A leaf stores the frequency or weight of one symbol. -/
  | leaf (symbolWeight : Nat)
  /-- A branch merges two subtrees. -/
  | node (left right : HuffmanTree)

/-- Total symbol weight below a Huffman-tree node. -/
def HuffmanTree.weight : HuffmanTree → Nat
  | .leaf w => w
  | .node left right => left.weight + right.weight

/-- Weighted external path length, starting at depth `depth`. -/
def HuffmanTree.externalCost : Nat → HuffmanTree → Nat
  | depth, .leaf w => depth * w
  | depth, .node left right =>
      left.externalCost (depth + 1) + right.externalCost (depth + 1)

/-- The codewords obtained by labelling left edges `false` and right edges `true`. -/
def HuffmanTree.codewords : HuffmanTree → List (List Bool)
  | .leaf _ => [[]]
  | .node left right =>
      left.codewords.map (false :: ·) ++ right.codewords.map (true :: ·)

/-- No distinct codeword is a prefix of another. -/
def PrefixFree (codes : List (List Bool)) : Prop :=
  ∀ ⦃x⦄, x ∈ codes → ∀ ⦃y⦄, y ∈ codes → x.IsPrefix y → x = y

/-- Increasing every leaf depth by one adds exactly the tree's total weight. -/
theorem HuffmanTree.externalCost_succ (tree : HuffmanTree) (depth : Nat) :
    tree.externalCost (depth + 1) = tree.externalCost depth + tree.weight := by
  induction tree generalizing depth with
  | leaf w =>
      simp [HuffmanTree.externalCost, HuffmanTree.weight]
      ring
  | node left right left_ih right_ih =>
      simp [HuffmanTree.externalCost, HuffmanTree.weight, left_ih, right_ih]
      ring

/-- Codewords generated by a Huffman tree are prefix-free. -/
theorem HuffmanTree.prefixFree_codewords (tree : HuffmanTree) :
    PrefixFree tree.codewords := by
  induction tree with
  | leaf w =>
      intro x hx y hy _
      simp [HuffmanTree.codewords] at hx hy
      exact hx.trans hy.symm
  | node left right left_ih right_ih =>
      simp [PrefixFree, HuffmanTree.codewords] at left_ih right_ih ⊢
      aesop

/-- A job has a duration, deadline, and profit. -/
structure Job where
  duration : Nat
  deadline : Nat
  profit : Nat

/-- The total elapsed processing time of a job list. -/
def scheduledTime (jobs : List Job) : Nat :=
  (jobs.map Job.duration).sum

/-- The total profit of a scheduled job list. -/
def totalProfit (jobs : List Job) : Nat :=
  (jobs.map Job.profit).sum

/-- Deadline feasibility, parameterized by time already elapsed. -/
def MeetsDeadlines : Nat → List Job → Prop
  | _, [] => True
  | elapsed, job :: jobs =>
      elapsed + job.duration ≤ job.deadline ∧
      MeetsDeadlines (elapsed + job.duration) jobs

end Game.Greedy
