import Game.Metadata
import Game.Support.GreedyExercises

open Game.Greedy

World "GreedyExercises"
Level 5
Title "Huffman Prefix Code"

Introduction "Huffman trees assign `false` to every left edge and `true` to every
right edge. Induct on the tree to prove that no generated codeword is a strict
prefix of another; codewords from opposite branches start with different bits."

/-- Codewords generated by a Huffman tree are prefix-free. -/
Statement (tree : HuffmanTree) : PrefixFree tree.codewords := by
  Hint "The tree-level lemma packages the induction over left and right
  branches."
  exact HuffmanTree.prefixFree_codewords tree

Conclusion "Every Huffman tree produces a prefix-free code."

NewTactic exact
NewDefinition Game.Greedy.HuffmanTree Game.Greedy.HuffmanTree.leaf Game.Greedy.HuffmanTree.node
  Game.Greedy.HuffmanTree.codewords Game.Greedy.PrefixFree List.IsPrefix
NewTheorem Game.Greedy.HuffmanTree.prefixFree_codewords
