import Game.Metadata
import Game.Support.AdvancedComplexity

open Game.Complexity
open Game.AdvancedComplexity

World "AdvancedComplexity"
Level 2
Title "Tseitin Gate Completeness"
-- source: ../game/Game/Worlds/W13AdvancedComplexity/L02CanonicalGates.lean

Introduction "The semantic assignment that gives each auxiliary variable its
subformula's truth value should satisfy every local gate clause generated by
`Tseitin.gates`."

Statement tseitin_gates_complete (f : Formula) (a : Nat → Bool) :
    evalGenericCNF3 (Tseitin.canonicalAssignment a) (Tseitin.gates f) = true := by
  Hint "Induct on `f`, then simplify the generated clauses."
  induction f with
  | atom n =>
      simp [Tseitin.gates, Tseitin.aux, Tseitin.atom, Tseitin.clause,
        evalGenericCNF3, evalGenericClause3, SignedLiteral.eval,
        SignedLiteral.pos, SignedLiteral.neg, Tseitin.canonicalAssignment,
        Formula.eval]
  | falsum =>
      simp [Tseitin.gates, Tseitin.aux, Tseitin.clause, evalGenericCNF3,
        evalGenericClause3, SignedLiteral.eval, SignedLiteral.neg,
        Tseitin.canonicalAssignment, Formula.eval]
  | neg f ih =>
      simp_all [Tseitin.gates, Tseitin.aux, Tseitin.clause,
        evalGenericCNF3, evalGenericClause3, SignedLiteral.eval,
        SignedLiteral.pos, SignedLiteral.neg, Tseitin.canonicalAssignment,
        Formula.eval]
  | conj left right ihLeft ihRight =>
      simp_all [Tseitin.gates, Tseitin.aux, Tseitin.clause,
        evalGenericCNF3, evalGenericClause3, SignedLiteral.eval,
        SignedLiteral.pos, SignedLiteral.neg, Tseitin.canonicalAssignment,
        Formula.eval]
      cases Formula.eval a left <;> cases Formula.eval a right <;> simp
  | disj left right ihLeft ihRight =>
      simp_all [Tseitin.gates, Tseitin.aux, Tseitin.clause,
        evalGenericCNF3, evalGenericClause3, SignedLiteral.eval,
        SignedLiteral.pos, SignedLiteral.neg, Tseitin.canonicalAssignment,
        Formula.eval]
      cases Formula.eval a left <;> cases Formula.eval a right <;> simp

Conclusion "Every local Tseitin gate is satisfied by the canonical assignment."

NewDefinition Game.AdvancedComplexity.GenericClause3
  Game.AdvancedComplexity.GenericCNF3
  Game.AdvancedComplexity.evalGenericClause3
  Game.AdvancedComplexity.evalGenericCNF3
  Game.AdvancedComplexity.TseitinVariable
  Game.AdvancedComplexity.Tseitin.aux
  Game.AdvancedComplexity.Tseitin.atom
  Game.AdvancedComplexity.Tseitin.clause
  Game.AdvancedComplexity.Tseitin.gates
  Game.AdvancedComplexity.Tseitin.canonicalAssignment
